[project]
name = "mist"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "einops>=0.8.2",
  "h5py>=3.16.0",
  "hyperopt>=0.2.7",
  "matplotlib==3.4.*",
  "mkl==2024.0.*",
  "optuna>=4.8.0",
  "pathos>=0.3.5",
  "pytorch-lightning==1.6.*",
  "ray[air]>=2.48.0",
  "ray-lightning",
  "rdkit>=2025.9.6",
  "scikit-learn>=1.7.2",
  "seaborn==0.11.*",
  "umap-learn>=0.5.11",
  "cairosvg>=2.9.0",
  "setuptools==59.5.0",
  "pygobject==3.50.0",
  "ipykernel>=7.2.0",
  "ipywidgets>=8.1.8",
  "polars>=1.39.3",
]

[tool.uv.sources]
ray-lightning = { git = "https://github.com/ray-project/ray_lightning" }

[build-system]
requires = ["uv_build>=0.11.2,<0.12"]
build-backend = "uv_build"
